"""unique report decision_id

Revision ID: 6da2019cd3f4
Revises: e51bba01bfb4
Create Date: 2026-06-02 05:50:35.794679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da2019cd3f4'
down_revision: Union[str, None] = 'e51bba01bfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reports', ['decision_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    # ### end Alembic commands ###
